# Generated by Django 5.2.6 on 2025-09-30 01:45

import crm.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_enable_btree_gist'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.UUIDField(db_index=True)),
                ('detail_code', models.CharField(max_length=100)),
                ('value', models.JSONField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('hashdiff', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uid', 'detail_code'), name='unique_current_detail'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(crm.models.TsTzRange('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('entity_uid', '='), ('detail_code', '=')], name='exclude_overlapping_detail_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('display_name', models.TextField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='crm.entitytype')),
            ],
            options={
                'indexes': [models.Index(fields=['entity_uid'], name='crm_entity_entity__f66991_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('entity_uid',), name='unique_current_entity'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[(crm.models.TsTzRange('valid_from', 'valid_to', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), ('entity_uid', '=')], name='exclude_overlapping_entity_uid')],
            },
        ),
    ]
