# Generated by Django 5.2.6 on 2025-10-04 21:04

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entity',
            index=django.contrib.postgres.indexes.GinIndex(fields=['display_name'], name='entity_display_name_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
