version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: cockpit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn cockpit.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=cockpit_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data: